language: python
env:
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=docs
    - TOXENV=py2-cover,py3-cover,coverage
install:
    - travis_retry pip install tox
script:
    - travis_retry tox

